### ISSUE TITLE
Duplicate ratings created if called multiple times

### ISSUE THREAD

**Issue by jslaybaugh** [ripter/jquery.rating#1]
I know it sounds like this is probably a feature and not a bug, but i have a heavily-ajaxy form that shows and hides panels and needs to call .rating() each time.  when it does that, you end up with several rating controls for 1 select box.  I edited the source in my app to add one line to remove it, but i'm not 100% sure this is foolproof, so i thought I'd let you know and you could see if it was worth adding in a future version.

in the section at the bottom where you "process the matched elements," i made the following edit:

```
        //We only do select types
        if ($(this).attr("type") !== "select-one") { return; }
        //Save 'this' for ease of development
        var selectBox = this;

        // custom code to stop duplicate creation
        if ($(selectBox).siblings("div").length > 0) return false;
        // end custom code

        //Hide the selectBox
        $(selectBox).css("display", "none");
        ...
```

**Comment by ripter** [comment]
Good catch! 
Calling it multiple times really shouldn't create the control more than once, I'll make sure to include the fix on my next update.
Thanks!
