### ISSUE TITLE
First star selected by default

### ISSUE THREAD

**Issue by pierrea** [ripter/jquery.rating#15]
The first star is selected even when there is no rating yet.

This is due to the fact that the first `<option>` of my `<select>` element is set as selected when no one else is.
Even if there is no `selected="selected"` parameter in the <option> element, I can see that with the inspector (firebug). So does jQuery see this element as selected.

I don't know why you don't have the problem and how to avoid it... Thanks!

**Comment by CharlyBrok** [comment]
You have to put an empty value first : `<option value="">Cancel</option>`.

**Comment by LucitheR** [comment]
@CharlyBrok  thanks, had the same Problem
